name: Test ConfigMyPy

on: [push, pull_request]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v3
    - name: Set up Python 3.9
      uses: actions/setup-python@v4
      with:
        python-version: 3.9
    - name: Install dependencies
      run: |
        python -m pip install --upgrade pip
    - name: Install package
      run: |
        python -m pip install -e .
    - name: Test with pytest
      run: |
        pytest -vvv src/configmypy